# Generated by Django 4.1.1 on 2022-09-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="date_joined",
            field=models.DateTimeField(
                default="2000-01-01", verbose_name="Date Joined"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateField(default="2001-01-01", verbose_name="Last Login"),
        ),
    ]
