# Generated by Django 4.1.1 on 2022-09-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_date_joined_alter_account_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date_joined",
            field=models.DateTimeField(verbose_name="Date Joined"),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(verbose_name="Last Login"),
        ),
    ]
