# Generated by Django 4.1.1 on 2022-09-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0005_alter_account_date_joined_alter_account_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="user_permissions",
            field=models.ManyToManyField(to="auth.permission"),
        ),
    ]
