# Generated by Django 4.1.1 on 2022-09-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_account_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="username",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
