# Generated by Django 4.1.1 on 2022-09-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_account_email_account_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="email",
        ),
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
        migrations.AlterField(
            model_name="account",
            name="date_joined",
            field=models.DateTimeField(auto_now=True, verbose_name="Date Joined"),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Last Login"),
        ),
    ]
