# Generated by Django 4.1.1 on 2022-09-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="start_date",
            field=models.DateField(auto_now=True),
        ),
    ]
