# Generated by Django 4.1.1 on 2022-09-22 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_friendship_delete_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="account_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="friend_id",
        ),
        migrations.AddField(
            model_name="friendship",
            name="friend_id",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
