# Generated by Django 4.1.1 on 2022-09-22 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_friendship_account_id_remove_friendship_friend_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendship",
            name="friend_id",
        ),
        migrations.AddField(
            model_name="friendship",
            name="friend_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
