# Generated by Django 4.1.1 on 2022-09-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_friendship_friend_id_friendship_friend_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendship",
            old_name="account_id",
            new_name="account",
        ),
        migrations.RenameField(
            model_name="friendship",
            old_name="friend_id",
            new_name="friend",
        ),
    ]
