# Generated by Django 4.1.1 on 2022-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_rename_account_id_friendship_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="full_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
