# Generated by Django 4.1.1 on 2022-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_account_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="full_name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
